base: 'https://typo3-project.ddev.site'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
dependencies:
  - yac-dev/frontendset
rootPageId: 1
routes: {  }
