styles.templates.layoutRootPath: EXT:frontendtemplate/Resources/Private/Layouts/
styles.templates.partialRootPath: EXT:frontendtemplate/Resources/Private/Partials/Content/
styles.templates.templateRootPath: EXT:frontendtemplate/Resources/Private/Templates/Content/